// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-vPr32LMGl-tZrGsoibwwUnhiim9NTc',
    appId: '1:533105080399:web:c83228968128970c10123a',
    messagingSenderId: '533105080399',
    projectId: 'freespc-2026',
    authDomain: 'freespc-2026.firebaseapp.com',
    storageBucket: 'freespc-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Wge3SbMBdc4vJtl35oXgJVqo1AkXuI0',
    appId: '1:533105080399:android:c7387cad2567f6b310123a',
    messagingSenderId: '533105080399',
    projectId: 'freespc-2026',
    storageBucket: 'freespc-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwQIx-DHkzJ4vg0pfZjuHzCPtsRtXB7vk',
    appId: '1:533105080399:ios:5ea9ec25533bf33a10123a',
    messagingSenderId: '533105080399',
    projectId: 'freespc-2026',
    storageBucket: 'freespc-2026.firebasestorage.app',
    iosBundleId: 'com.freespc.freespc',
  );
}
